### ISSUE TITLE
.net 3.5 compability for unity3d?

### ISSUE THREAD

**Issue by friuns2** [kevin-montrose/LinqAF#2]
Hi can you add support for .net 3.5 for unity3d?

**Comment by NVentimiglia** [comment]
+1

Performance sensitive applications, like games, would benefit from this the most

**Comment by kevin-montrose** [comment]
Release [1.2.0](https://github.com/kevin-montrose/LinqAF/releases/tag/1.2.0) (pending indexing on Nuget atm, but [available](https://www.nuget.org/packages/LinqAF/1.2.0)) now includes a .NET 3.5 build.  Major difference is that all `SortedSet<T>` operations are #if'd out.
